apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: public.ecr.aws/nginx/nginx:1.23
    - name: busybox-container
      image: public.ecr.aws/docker/library/busybox:latest